Repository NeoA11y/SpeakTouch, pull requests merged in 2023-11, with the labels that each got.

#82 Improve Node Scan DSL
  app/src/main/java/com/neo/speaktouch/controller/FocusController.kt
  app/src/main/java/com/neo/speaktouch/utils/extension/AccessibilityNodeInfo.kt
  app/src/main/java/com/neo/speaktouch/utils/extension/NodeScan.kt
  app/src/main/java/com/neo/speaktouch/utils/extension/NodeScanDSL.kt
Labels: refactor

#76 Fix mandatory focus
  app/src/main/java/com/neo/speaktouch/utils/object/NodeValidator.kt
  test/src/main/java/com/neo/test/fragment/MustFocusFragment.kt
  test/src/main/res/layout/activity_main.xml
  test/src/main/res/layout/fragment_must_focus.xml
  test/src/main/res/values-night/themes.xml
  test/src/main/res/values/themes.xml
Labels: bug

#87 Implement most important gestures
  app/src/main/java/com/neo/speaktouch/intercepter/GestureInterceptor.kt
  app/src/main/java/com/neo/speaktouch/model/Reader.kt
  app/src/main/java/com/neo/speaktouch/service/SpeakTouchService.kt
  app/src/main/res/xml-v31/accessibility_service_config.xml
Labels: feature, good first issue

#78 Implement exploration gestures
  app/build.gradle.kts
  app/src/debug/res/values/strings.xml
  app/src/main/java/com/neo/speaktouch/controller/FocusController.kt
  app/src/main/java/com/neo/speaktouch/intercepter/CallbackInterceptor.kt
  app/src/main/java/com/neo/speaktouch/intercepter/GestureInterceptor.kt
  app/src/main/java/com/neo/speaktouch/model/NodeFilter.kt
  app/src/main/java/com/neo/speaktouch/model/Reader.kt
  app/src/main/java/com/neo/speaktouch/service/SpeakTouchService.kt
  app/src/main/java/com/neo/speaktouch/utils/extension/AccessibilityNodeInfo.kt
  app/src/main/java/com/neo/speaktouch/utils/extension/NodeScan.kt
  app/src/main/res/xml-v31/accessibility_service_config.xml
  test/src/main/java/com/neo/test/fragment/ExplorationFragment.kt
  test/src/main/res/drawable/bg_black_border.xml
  test/src/main/res/drawable/bg_read_border.xml
  test/src/main/res/layout/activity_main.xml
  test/src/main/res/layout/fragment_exploration.xml
Labels: feature

#114 Read empty edit text
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  app/src/main/java/com/neo/speaktouch/utils/NodeValidator.kt
Labels: bug, small

#117 Build and upload APKs as artifacts
  .github/workflows/build.yml
  app/build.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
  gradlew
Labels: ci/cd

#116 Add Gradle dependency verification metadata
  gradle/libs.versions.toml
  gradle/verification-metadata.xml
Labels: build, security

#100 Improve Reader class
  app/src/main/java/com/neo/speaktouch/controller/SpeechController.kt
  app/src/main/java/com/neo/speaktouch/di/module/ControllerModule.kt
  app/src/main/java/com/neo/speaktouch/model/Text.kt
  app/src/main/java/com/neo/speaktouch/model/Type.kt
  app/src/main/java/com/neo/speaktouch/utils/NodeValidator.kt
  app/src/main/java/com/neo/speaktouch/utils/Reader.kt
  app/src/main/java/com/neo/speaktouch/utils/extension/AccessibilityNodeInfo.kt
  app/src/main/java/com/neo/speaktouch/utils/extension/CharSequence.kt
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values/strings.xml
  test/src/main/java/com/neo/test/checkable/CustomCheckable.kt
  test/src/main/java/com/neo/test/fragment/SwitchesFragment.kt
  test/src/main/res/layout/activity_main.xml
  test/src/main/res/layout/fragment_switches.xml
Labels: refactor

#123 Set debug app name more concisely
  app/build.gradle.kts
  app/src/debug/res/values/strings.xml
Labels: build
