Repository NeoA11y/SpeakTouch, pull requests merged in 2023-09, with the labels that each got.

#45 [Feature/ST40] review node reading
  .idea/codeStyles/Project.xml
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/migrations.xml
  app/src/main/java/com/neo/speaktouch/intercepter/FocusInterceptor.kt
  app/src/main/java/com/neo/speaktouch/intercepter/SpeechInterceptor.kt
  app/src/main/java/com/neo/speaktouch/model/Reader.kt
  app/src/main/java/com/neo/speaktouch/model/Type.kt
  app/src/main/java/com/neo/speaktouch/model/UiText.kt
  app/src/main/java/com/neo/speaktouch/service/SpeakTouchService.kt
  app/src/main/java/com/neo/speaktouch/utils/extension/AccessibilityEvent.kt
  app/src/main/java/com/neo/speaktouch/utils/extension/AccessibilityNodeInfo.kt
  app/src/main/java/com/neo/speaktouch/utils/extension/CharSequence.kt
  app/src/main/java/com/neo/speaktouch/utils/extension/Context.kt
  app/src/main/java/com/neo/speaktouch/utils/extension/Iterable.kt
  app/src/main/java/com/neo/speaktouch/utils/object/NodeValidator.kt
  app/src/main/java/com/neo/speaktouch/utils/typealias/NodeInfo.kt
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values/strings.xml
  test/build.gradle.kts
  test/src/main/java/com/neo/test/MainActivity.kt
  test/src/main/java/com/neo/test/fragment/SwitchesFragment.kt
  test/src/main/res/layout/activity_main.xml
  test/src/main/res/layout/fragment_switches.xml
  test/src/main/res/layout/include_custom_switcher.xml
  test/src/main/res/layout/include_invalid_custom_switcher.xml
Labels: enhancement

#51 Create issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .idea/misc.xml
Labels: documentation

#55 Create pull request template
  .github/pull_request_template.md
Labels: documentation

#58 Update dependencies, migrate to version catalog
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  test/build.gradle.kts
Labels: build, refactor

#60 Create feature request template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#54 App is focusing on non-readable ViewGroup
  app/src/main/java/com/neo/speaktouch/intercepter/FocusInterceptor.kt
  app/src/main/java/com/neo/speaktouch/model/Reader.kt
  app/src/main/java/com/neo/speaktouch/utils/extension/AccessibilityNodeInfo.kt
  app/src/main/java/com/neo/speaktouch/utils/extension/CharSequence.kt
  app/src/main/java/com/neo/speaktouch/utils/object/NodeValidator.kt
Labels: bug, documentation, refactor
