Repository NeoA11y/SpeakTouch, pull requests merged in 2023-12, with the labels that each got.

#124 Add support for Jetpack Compose Role.Button
  app/src/main/java/com/neo/speaktouch/controller/SpeechController.kt
  app/src/main/java/com/neo/speaktouch/utils/Node.kt
  app/src/main/java/com/neo/speaktouch/utils/NodeValidator.kt
  app/src/main/java/com/neo/speaktouch/utils/Reader.kt
  app/src/main/java/com/neo/speaktouch/utils/extension/Iterable.kt
  test/src/main/java/com/neo/test/fragment/ReadChildrenFragment.kt
  test/src/main/res/layout/activity_main.xml
  test/src/main/res/layout/fragment_read_children.xml
Labels: bug, feature

#128 App does not work in flutter apps
  app/src/main/java/com/neo/speaktouch/controller/FocusController.kt
  app/src/main/java/com/neo/speaktouch/controller/SpeechController.kt
  app/src/main/java/com/neo/speaktouch/intercepter/event/FocusInterceptor.kt
  app/src/main/java/com/neo/speaktouch/model/NodeFilter.kt
  app/src/main/java/com/neo/speaktouch/utils/Node.kt
  app/src/main/java/com/neo/speaktouch/utils/NodeValidator.kt
  app/src/main/java/com/neo/speaktouch/utils/Reader.kt
  app/src/main/java/com/neo/speaktouch/utils/extension/AccessibilityNodeInfo.kt
  test/src/main/res/layout/fragment_must_focus.xml
  test/src/main/res/layout/fragment_read_children.xml
Labels: bug, attention

#126 Must focus on interactive container
  app/src/main/java/com/neo/speaktouch/utils/NodeValidator.kt
  buildSrc/settings.gradle.kts
  settings.gradle.kts
  test/src/main/java/com/neo/test/fragment/ReadChildrenFragment.kt
  test/src/main/res/layout/fragment_read_children.xml
Labels: bug

#131 build: refactor, update Kotlin to v1.9.22
  .github/workflows/build.yml
  .idea/kotlinc.xml
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
  buildSrc/src/main/kotlin/VersionConfig.kt
  gradle.properties
  gradle/libs.versions.toml
  gradle/verification-metadata.xml
  settings.gradle.kts
  test/build.gradle.kts
Labels: build, refactor, ci/cd
