Repository NeoA11y/SpeakTouch, pull requests merged in 2023-04, with the labels that each got.

#31 Update gradle to v8.1.1
  gradle/wrapper/gradle-wrapper.properties
Labels: build

#32 [Hotfix/SP27] not reading containers correctly
  app/src/main/java/com/neo/speaktouch/intercepter/FocusInterceptor.kt
  app/src/main/java/com/neo/speaktouch/intercepter/SpeechInterceptor.kt
  app/src/main/java/com/neo/speaktouch/intercepter/interfece/Interceptor.kt
  app/src/main/java/com/neo/speaktouch/service/SpeakTouchService.kt
  app/src/main/java/com/neo/speaktouch/utils/extensions/AccessibilityNodeInfo.kt
Labels: bug, hotfix

#33 [Release/v0.1.2] Prototype - Patch 2
  app/build.gradle
  app/src/main/java/com/neo/speaktouch/intercepter/FocusInterceptor.kt
  app/src/main/java/com/neo/speaktouch/intercepter/SpeechInterceptor.kt
  app/src/main/java/com/neo/speaktouch/intercepter/interfece/Interceptor.kt
  app/src/main/java/com/neo/speaktouch/service/SpeakTouchService.kt
  app/src/main/java/com/neo/speaktouch/utils/extensions/AccessibilityNodeInfo.kt
Labels: bug
